name: 'Setup Node Environment'
description: 'Checkout code, setup Bun, and install dependencies'
inputs:
  fetch-depth:
    description: 'Number of commits to fetch (0 for all history)'
    required: false
    default: '1'
  frozen-lockfile:
    description: 'Use frozen lockfile for install'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        # If we update Bun, we must change here as well!
        bun-version: 1.2.7 

    - name: Install dependencies
      run: bun install ${{ inputs.frozen-lockfile == 'true' && '--frozen-lockfile' || '' }}
      shell: bash
