name: Release

on:
  workflow_run:
    workflows: ["check-test-build"]
    branches: [main]
    types: [completed]

env:
  BUN_VERSION: 1.2.7

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # Only run if the CI workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Setup Node environment
        uses: ./.github/actions/setup-node-env
        with:
          fetch-depth: 0

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Setup and run semantic release
        uses: ./.github/actions/semantic-release
        with:
          dry-run: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          bun-version: ${{ env.BUN_VERSION }}